### ISSUE TITLE
1.4

### ISSUE THREAD

**Issue by AtharvePandey** [AtharvePandey/C-book-excercises#1]
In process of writing exercise 1.4 solution; too lazy but if you want, go through the book, and then complete 1.4 and make a pull request

**Comment by Harshal662** [comment]
i can do it

**Comment by AtharvePandey** [comment]
yeah go for it, also let me know when you finish by doing a pull request

**Comment by Harshal662** [comment]
I have to make cel to far converter right? 

And in book the example given is far to cel.

**Comment by AtharvePandey** [comment]
yes sir
