### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by AtharvePandey** [AtharvePandey/C-book-excercises#2]
can't seem to run the code properly even though it can compile successfully without warning; when i do ./1.8 to run the 8th excercise file in the terminal, it just stops there and doesnt do anything....

**Comment by Harshal662** [comment]
After compiling i ran the .exe file in that we have to give input and press (ctrl+c, eding the program) to get the output.

**Comment by AtharvePandey** [comment]
oh ok thanks! i gave input but didnt know you had to press control c.
